name: Sample
options:
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2
  bundleIdPrefix: "io.wtr.sample"
settings:
  DEVELOPMENT_TEAM: "23P2WNBSHC"
targets:
  SampleApp:
    type: application
    platform: iOS
    sources:
      - path: sample
    preBuildScripts:
      - path: /bin/sh
        name: Run Swiftlint
        script: |
          SWIFT_LINT="swift run swiftlint" 2> /dev/null

          git diff  --diff-filter=d --name-only | grep "\.swift" | while read filename; do
            ${SWIFT_LINT} lint --path "${filename}"
          done
  SampleAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SampleAppTests
    dependencies:
      - target: SampleApp
  SampleAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SampleAppUITests
    dependencies:
      - target: SampleApp